image: python:3.11

stages:
  - test

before_script:
  - pip install -r requirements.txt

test:local:
  stage: test
  image: selenium/standalone-chrome:latest
  script:
    - pytest steps/ --headless --env=local --html=reports/report.html --self-contained-html
  artifacts:
    when: always
    paths:
      - reports/
    expire_in: 7 days